language: java
jdk: oraclejdk7
sudo: false
install:
- mvn --version
before_script:
- export DISPLAY=:99
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- cd info.limpet.targetplatforms
- mvn clean install
- cd ..
- mvn clean verify -U -B -fae
- ./deploy_ghpages.sh
env:
  global:
  - GH_REF: github.com/debrief/limpet-release.git
  - secure: VKM/Cae1fBwZgR7+U2ea9PpuuIZ09OEAJtjDcSwGq5evTdIKRAdfnIWFUbloFiELefRKlr9fUuz3xg816uajn3HxWDrEfc5GWKAvrWhvrXrVMjc0Laa6qtl1K8dHcxeLY8d0WDg/1CUg42j1eGulu3T9YuZdfhu+n6Tmvgh98hb0xwpJw0UToSI+CM8WdLVxaxK5sXMr+ZoFuraEU5LyHixz7cWomBXGmhxmHhuMlLN6wPhQelI/yOPOB+r3CrdbqioEp1+QsnEi8GR+0nrIOplg/i76R6XibfZ483dZKNMsSmV66uqrQn0HxFE8z1xvYXZ8GXLZhHIX46kpb9Xifa/Wx94W0zTZdO4Sj8QwzhM2Ju/hiC98zdnNGTv0+noJljzfcyrpjLwWOzJvHmbAsghe8nfWvWcLzJv6Cc1N6V0ks1B7RT+Ju02ST+1PuWu/mAoZV0ZDlC5oxH0GdFaaKMki7TneZ5jTRyO5qUZAGqOJUHvfKhviWjcngs+wG+F4Ye3dZsTClSuSSnfYJLs7YLHGI/kBwkBB3KnqNnzyfx9Ndj3cHFJVqcnNTOMVXWiIwccP6+Ek5tgoW8lIjkwOa5+en6zJQBiKBF8HT63YQ9hMLk5AKKmd/3HDVnQJUBN1r/jnoFE11sA78MUj4qX+YrdadFyzxAdlaR6nlmnQl5g=
