language: java
jdk: oraclejdk7
sudo: false
install: 
- mvn --version
before_script:
- export DISPLAY=:99
- sh -e /etc/init.d/xvfb start
- sleep 3
script: 
- cd info.limpet.targetplatforms
- mvn clean install
- cd ..
- mvn clean verify -U -B -fae
