/**
 *
 * $Id$
 */
package info.limpet.stackedcharts.model.validation;

import info.limpet.stackedcharts.model.AxisOrigin;
import info.limpet.stackedcharts.model.AxisScale;
import info.limpet.stackedcharts.model.Chart;

/**
 * A sample validator interface for {@link info.limpet.stackedcharts.model.Axis}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AxisValidator
{
  boolean validate();

  boolean validateParent(Chart value);
  boolean validateName(String value);
  boolean validateOrigin(AxisOrigin value);
  boolean validateScale(AxisScale value);
}
