/**
 *
 * $Id$
 */
package info.limpet.stackedcharts.model.validation;

import info.limpet.stackedcharts.model.Chart;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link info.limpet.stackedcharts.model.ChartSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChartSetValidator
{
  boolean validate();

  boolean validateCharts(EList<Chart> value);
}
