/**
 *
 * $Id$
 */
package info.limpet.stackedcharts.model.validation;

import info.limpet.stackedcharts.model.Annotation;
import info.limpet.stackedcharts.model.Axis;
import info.limpet.stackedcharts.model.ChartSet;
import info.limpet.stackedcharts.model.Dataset;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link info.limpet.stackedcharts.model.Chart}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChartValidator
{
  boolean validate();

  boolean validateParent(ChartSet value);
  boolean validateAxes(EList<Axis> value);
  boolean validateDatasets(EList<Dataset> value);
  boolean validateName(String value);
  boolean validateAnnotations(EList<Annotation> value);
}
