/**
 *
 * $Id$
 */
package info.limpet.stackedcharts.model.validation;

import info.limpet.stackedcharts.model.Axis;
import info.limpet.stackedcharts.model.DataItem;
import info.limpet.stackedcharts.model.Styling;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link info.limpet.stackedcharts.model.Dataset}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DatasetValidator
{
  boolean validate();

  boolean validateName(String value);
  boolean validateAxis(Axis value);
  boolean validateItems(EList<DataItem> value);
  boolean validateStyling(Styling value);
}
