/**
 *
 * $Id$
 */
package info.limpet.stackedcharts.model.validation;


/**
 * A sample validator interface for {@link info.limpet.stackedcharts.model.DataItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataItemValidator
{
  boolean validate();

  boolean validateIndependentVal(double value);
  boolean validateDependentVal(double value);
}
